disabled_rules:
  - trailing_whitespace
  - nesting
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_acl
  - explicit_top_level_acl
  - lower_acl_than_parent
  - first_where
  - joined_default_parameter
  - overridden_super_call
  - private_outlet
  - private_action
  - unused_import
  - yoda_condition
excluded:
  - Carthage
  - Pods

trailing_whitespace:
  ignores_empty_lines: true
function_parameter_count:
  warning: 9
  error: 12
function_body_length:
  warning: 60
  error: 100
cyclomatic_complexity:
  warning: 40
  error: 60
type_body_length:
  warning: 400
  error: 500
line_length:
  warning: 250
  error: 400
file_length:
  warning: 700
  error: 1200
type_name:
    min_length: 3
    max_length:
      warning: 50
      error: 60
identifier_name:
  min_length: 3
  max_length: 50
  excluded:
    - i
    - to
    - x
    - y
    - z
    - a
    - b
    - ac
    - vc
    - map
    - app
    - id    
reporter: "xcode"
